### PR TITLE
Fixes Message not being Sent #149

### PR DESCRIPTION
**Pull request by Naman23-coder**
resolves https://github.com/Ankit404butfound/PyWhatKit/issues/149

### CODE REVIEW

**Comment by aaryanrr** [comment]
Hey @Naman23-coder, thanks for the contribution. We'll review this PR soon!

**Comment by douglaslo** [comment]
Hello, I am quite new to coding and github, but it seems to be that the proposed solution would fix the problem. But apparently this version of the code is not yet released. May I know when it will be released. Also, what is the best way of getting this version of the code for my personal use?

**Comment by Naman23-coder** [comment]
@douglaslo it is currently under testing, it will be released soon

**Comment by aaryanrr** [comment]
merged :tada:

**Pull request merged**
