### PR TITLE
Added sending images at certain time, not just instant.

### PR DESCRIPTION
**Pull request by MohamedAly8**
Added the same functionality for images to be sent at a certain time similar to how text messages can be sent at any time. The algorithm used is the exact same as the one for text messages.

### CODE REVIEW

**Comment by MohamedAly8** [comment]
This is also my first ever open-source contribution! Please let me know if I misunderstood a step I would be more than happy to fix it.

**Comment by Naman23-coder** [comment]
@MohamedAly8 please run `pre-commit run --all-files` and push again

**Comment by MohamedAly8** [comment]
@Naman23-coder done!

**Comment by aaryanrr** [comment]
Merged :tada:

**Pull request merged**
