### PR TITLE
Merge the new repo

### PR DESCRIPTION
**Pull request by codewithpom**
Merge them

### CODE REVIEW

**Comment by aaryanrr** [comment]
Hey @codewithpom, we are currently in the middle of a rewrite of the whole library for the 5.2 update. We'll review your PR once we are finished with the Update.

**Comment by codewithpom** [comment]
Ok

**Comment by codewithpom** [comment]
Can I even help you in this @aaryanrr

**Comment by aaryanrr** [comment]
Thanks for asking. We'll let you know if there is anything needed! You can Join the discord server for discussing possible features to Contribute.

**Comment by codewithpom** [comment]
It is me Padmashree

**Pull request closed without merging**
