### PR TITLE
new feature

### PR DESCRIPTION
**Pull request by Naman23-coder**

### CODE REVIEW

**Comment by Ankit404butfound** [comment]
Hello @Naman23-coder, that would be a helpful feature while creating Virtual assistant and such things, but before we merge the PR, you need to format the code according to Pep8 standard. This is to maintain the consistency. You can use autopep8 library to do so, then you can open a PR and we will merge it.

**Comment by Naman23-coder** [comment]
> Hello @Naman23-coder, that would be a helpful feature while creating Virtual assistant and such things, but before we merge the PR, you need to format the code according to Pep8 standard. This is to maintain the consistency. You can use autopep8 library to do so, then we will merge this PR.

ok will do that tom

**Comment by aaryanrr** [comment]
@Naman23-coder see the CONTRIBUTING.md for the guide on how to format the code

**Comment by Naman23-coder** [comment]
> @Naman23-coder see the CONTRIBUTING.md for the guide on how to format the code

Thanks I am just a noob in GitHub just a month experience

**Comment by aaryanrr** [comment]
You'll get to know everything with time. Keep Practicing!

**Comment by Naman23-coder** [comment]
done everything used autopep8 too! :1st_place_medal:

**Comment by Naman23-coder** [comment]
as soon as it is merge i would close this

**Comment by Ankit404butfound** [comment]
> Hey should I close this PR

No, don't worry about it, we are reviewing the PR, we will merge it after it's passes.

**Comment by Naman23-coder** [comment]
ok thanks

**Comment by Ankit404butfound** [comment]
> ok thanks

The PR has been merged, thanks for the contribution.

**Comment by Naman23-coder** [comment]
i am not on on discord 'cause i am under 13

**Pull request merged**
