### PR TITLE
Updated the file with latest bug fixtures

### PR DESCRIPTION
**Pull request by Himangshu-De**
Changed few lines in which I got bugs and made 'def cancel_shutdown():' independent from 'def shutdown():'

### CODE REVIEW

**Comment by aaryanrr** [comment]
Hey @Himangshu-De would you please the cause for this change?

**Comment by Himangshu-De** [comment]
> Hey @Himangshu-De would you please the cause for this change?

When I ran the program for the first time and called shutdown function to make my system shutdown in the specified time and the program ended. Now second time when I ran the same program and called cancelshutdown function it gave me an error namely "osname not defined", in order to fix  that i made the changes in both the functions which I hope you've already seen. Now if I run the program two times by calling two different functions at each execution will give no error now. 

I hope my reason is to the point and justified.
Looking forward for valuable reply.
Thank You

**Comment by aaryanrr** [comment]
Thanks for pointing the issue. We didn't knew about this. I'll merge the PR.

**Comment by Himangshu-De** [comment]
> Thanks for pointing the issue. We didn't knew about this. I'll merge the PR.

It's an honour for me to help you...
Have a great day 
Regards,
Himangshu De

**Pull request merged**
