### PR TITLE
Web Screenshotter

### PR DESCRIPTION
**Pull request by Sachit71**
# PyWhatkit's new proposed feature

## This feature is based on render-tron a headless chrome rendering solution,

Using rendertron we enter the link and the image are stored, in the directory as a jpg file, since PyWhatkit is all about data fetching, web scraping and sorts I think this feature will really fit in.

### CODE REVIEW

**Comment by aaryanrr** [comment]
@Sachit71, thanks for implementing this feature. Can you show us the source code of the service used in this feature?

**Comment by Sachit71** [comment]
@aaryanrr hey I have linked the services source code but here you go again https://github.com/GoogleChrome/rendertron

**Comment by aaryanrr** [comment]
Please move this feature to `misc.py`. And follow the contribution guidelines for formatting the code before committing.

**Comment by aaryanrr** [comment]
Hey @Sachit71, can you please close this PR and reopen it again. There seems to be some merge conflict issue.

**Pull request closed without merging**
