### PR TITLE
Version 5.2 - Update 2

### PR DESCRIPTION
**Pull request by aaryanrr**
Following Changes have been made:
- Fix for Group Message not Sending
- Updated Function Descriptions and Error Messages
- Minor Typo Fixes

### CODE REVIEW

**Comment by Delta456** [comment]
Really hoping to see https://github.com/Ankit404butfound/PyWhatKit/issues/116 fixed

**Comment by aaryanrr** [comment]
> Really hoping to see #116 fixed

Yep it has been fixed and tested!

**Comment by Delta456** [comment]
In which commit was this fixed? I wanna how it was done.

**Comment by aaryanrr** [comment]
This was a problem with `xclip`. We used it to copy the image to the clipboard but for some reason it wasn't pasting the image in WhatsApp web. Now with this update we are going to use [copyq](https://github.com/hluk/CopyQ). It is a more versatile clipboard manager. `Xclip` was replaced in [this](https://github.com/Ankit404butfound/PyWhatKit/pull/121/commits/5427dd81e1e3a90e216c5cffa3c4f2f007d6b85c) commit. This PR also adds some improvement to that function so it is less prone to bugs.

**Comment by Delta456** [comment]
Oh I see! Hope it comes out soon!

**Comment by aaryanrr** [comment]
Yep, Will be out by tomorrow as Ankit is busy with some work and each update has to be tested thoroughly before being released.

**Comment by Delta456** [comment]
Ok! Please take your time on it as it can be tested throughout and no bugs would be there when released.

**Comment by Delta456** [comment]
I don't wanna pest but are there any updates?

**Comment by aaryanrr** [comment]
Sorry for the delay in update. All the maintainers are currently busy with other stuff. We will release the update as soon as possible.

**Pull request merged**
