### PR TITLE
Check complete phone number instead of just country code

### LINKED ISSUE #178: Check complete phone number instead of just country code
Hi all,

Currently, the function to check the phone number is just checking the country code. Therefore no exception will be raised if the phone number is in an invalid format (for example : it has less than 10 digits)

I think this can be solved by checking the number with a regex expression. But since different countries have different phone number patterns, we have to take that into account too

Please let me know your thoughts

### PR DESCRIPTION
**Pull request by Siddhesh-Agarwal**
# Check complete phone number instead of just country code
- closes #178 
- **Changes:**
  - Created `InvalidPhoneNumber` Exception.
  - Cleaned phone number by removing spaces.
  - Raised `InvalidPhoneNumber` Exception when phone number did not satisfy regular expression.

### CODE REVIEW

**Comment by Naman23-coder** [comment]
@Siddhesh-Agarwal the lint is failng due to sort, please run `pre-commit run --all-files`

**Comment by Siddhesh-Agarwal** [comment]
> @Siddhesh-Agarwal the lint is failng due to isort, please run `pre-commit run --all-files`

For me it says `bash: pre-commit: command not found`

**Comment by Naman23-coder** [comment]
`pip install pre-commit`

**Comment by Siddhesh-Agarwal** [comment]
> `pip install pre-commit`

Thank you @Naman23-coder. It has worked and the PR has passed all checks

**Review by aaryanrr — APPROVED** [review]

**Comment by aaryanrr** [comment]
Merged :tada:

**Pull request merged**
