### PR TITLE
Add function sendwhatmsg_to_group_instantly

### PR DESCRIPTION
**Pull request by bharathbrat**
Adding functionality to send a message to a group instantly.

### CODE REVIEW

**Review by bharathbrat — COMMENTED** [review]
Fixed typo for lint

**Comment by Naman23-coder** [comment]
@bharathbrat seems good

**Comment by aaryanrr** [comment]
@bharathbrat thanks for the valuable contribution. Did you ran `pre-commit run --all-files` before pushing the changes?

**Comment by bharathbrat** [comment]
Definitely missed that step. I am a bit confused with what exactly lint was complaining about there. But it seems to have fixed something with pywhatkit/py.typed.

**Review by aaryanrr — APPROVED** [review]

**Comment by aaryanrr** [comment]
Thanks for the contribution!

**Pull request merged**
